Repository fosslight/fosslight_util, pull requests merged in 2021-06, with the labels that each got.

#12 Add files for reuse compliance
  .reuse/dep5
  LICENSES/Apache-2.0.txt
  README.md
  setup.py
  tox.ini
Labels: documentation

#13 Add lastversion to check the latest version of the package
  requirements.txt
  src/fosslight_util/set_log.py
  tests/test_log.py
  tox.ini
Labels: chore

#14 Change OSS report name to FOSSLight report
  README.md
  src/fosslight_util/write_excel.py
  tests/test_excel.py
  tox.ini
Labels: chore, documentation

#15 Modify Color log code using coloredlogs
  requirements.txt
  src/fosslight_util/set_log.py
Labels: chore

#16 Fix coloredlogs initial usage error
  src/fosslight_util/set_log.py
  tests/test_log.py
Labels: bug fix

#17 Delete unnecessary lines at tox.ini
  tox.ini
Labels: chore
