Repository fosslight/fosslight_util, pull requests merged in 2021-08, with the labels that each got.

#24 Add a header row for BIN_Android sheet
  src/fosslight_util/write_excel.py
Labels: chore, minor

#23 Merge init_log & init_log_item fct
  src/fosslight_util/set_log.py
  tests/_print_log.py
  tests/test_excel.py
  tests/test_log.py
  tests/test_text.py
Labels: chore

#26 Modify user guide to setup logger
  README.md
Labels: documentation

#28 Fix the bug where BIN (Android) cannot be printed
  src/fosslight_util/write_excel.py
Labels: bug fix

#29 Add exception for checking version
  src/fosslight_util/set_log.py
Labels: bug fix
