Repository fosslight/fosslight_util, pull requests merged in 2022-01, with the labels that each got.

#45 Add function for print package version
  src/fosslight_util/help.py
  tests/test_help.py
Labels: chore

#47 Change the upgrade message
  src/fosslight_util/set_log.py
Labels: documentation

#46 Add scanoss info on opossum
  src/fosslight_util/write_opossum.py
Labels: bug fix

#48 Modify to run github action for all branches when PR is created.
  .github/workflows/pull-request.yml
  src/fosslight_util/write_opossum.py
Labels: chore

#49 Support to output SRC and BIN sheets as opossum.
  src/fosslight_util/write_opossum.py
Labels: chore

#51 When outputting opossum format, cut as many columns as necessary.
  src/fosslight_util/write_opossum.py
Labels: chore
