Repository fosslight/fosslight_util, pull requests merged in 2022-07, with the labels that each got.

#74 Add the function to compare yaml
  .reuse/dep5
  src/fosslight_util/compare_yaml.py
  src/fosslight_util/write_opossum.py
  tests/after.yaml
  tests/before.yaml
  tests/test_compare_yaml.py
Labels: enhancement

#75 Fix the error to write opossum
  src/fosslight_util/write_opossum.py
Labels: bug fix

#76 Change error msg of parsing yaml error
  src/fosslight_util/parsing_yaml.py
Labels: chore

#77 Fix bug where relpath is printed differently in yaml
  src/fosslight_util/parsing_yaml.py
Labels: bug fix

#78 Add read_excel.py file
  src/fosslight_util/read_excel.py
Labels: chore

#79 Print warning msg when there is no matched sheet
  src/fosslight_util/read_excel.py
Labels: chore

#80 Fix not to create csv if format is empty
  src/fosslight_util/output_format.py
  src/fosslight_util/write_excel.py
Labels: chore

#81 Remove unnecessary return variables
  src/fosslight_util/write_yaml.py
Labels: chore

#82 Fix a bug that returns even if there is no result file.
  src/fosslight_util/output_format.py
Labels: bug fix

#83 Check null after removing empty sheet
  src/fosslight_util/output_format.py
  src/fosslight_util/write_excel.py
  src/fosslight_util/write_opossum.py
  src/fosslight_util/write_yaml.py
  tests/test_excel_and_csv.py
  tox.ini
Labels: chore
