Repository fosslight/fosslight_util, pull requests merged in 2022-02, with the labels that each got.

#52 Print output file(s) list
  src/fosslight_util/output_format.py
  src/fosslight_util/write_excel.py
  tests/test_output_format.py
Labels: chore

#54 Fix the opossum result to print the multiple resourcesToAttribution
  src/fosslight_util/write_opossum.py
  tests/test_opossum.py
Labels: bug fix

#55 When merging excel, add the option to create a csv file
  src/fosslight_util/write_excel.py
Labels: chore

#56 Install pygit2 according to python version
  requirements.txt
  setup.py
  tox.ini
Labels: chore

#57 Modify to get the source url for pypi
  src/fosslight_util/_get_downloadable_url.py
  tests/test_download.py
Labels: bug fix

#58 Comment out some sentences in the PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation
