Repository fosslight/fosslight_util, pull requests merged in 2023-05, with the labels that each got.

#113 Add to generate spdx format result
  requirements.txt
  src/fosslight_util/output_format.py
  src/fosslight_util/resources/frequent_license_nick_list.json
  src/fosslight_util/write_spdx.py
Labels: enhancement

#115 Fix the spdx-tools conflict issue
  requirements.txt
  src/fosslight_util/write_spdx.py
Labels: bug fix

#114 Fix the windows path for license resource
  src/fosslight_util/spdx_licenses.py
Labels: bug fix

#117 Fix the write_spdx bug
  src/fosslight_util/write_spdx.py
Labels: bug fix

#116 Modify condition to check output format
  src/fosslight_util/output_format.py
Labels: bug fix

#118 Fix the support default output format
  src/fosslight_util/output_format.py
Labels: bug fix

#119 Add the correction with sbom-info.yaml
  src/fosslight_util/correct.py
Labels: enhancement

#120 Fix to find the sbom-info.yaml file with pattern
  src/fosslight_util/correct.py
Labels: chore

#121 Fix to check exclude for correcting oss info
  src/fosslight_util/correct.py
Labels: chore
