Repository fosslight/fosslight_util, pull requests merged in 2023-08, with the labels that each got.

#127 Fix the pub download url
  src/fosslight_util/_get_downloadable_url.py
Labels: bug fix

#128 Fix the excel merge bug
  src/fosslight_util/write_excel.py
Labels: bug fix

#129 Generate ScanCode json result file
  src/fosslight_util/write_scancodejson.py
Labels: enhancement

#130 Fix the default oss name in oss list
  src/fosslight_util/compare_yaml.py
  src/fosslight_util/oss_item.py
Labels: bug fix

#131 [Snyk] Security upgrade setuptools from 39.0.1 to 65.5.1
  requirements.txt
Labels: chore

#132 Fix the vulnerability
  requirements.txt
  src/fosslight_util/download.py
Labels: chore

#134 Add the is_binary variable when printing the ScanCode.json file.
  src/fosslight_util/oss_item.py
  src/fosslight_util/read_excel.py
  src/fosslight_util/write_scancodejson.py
Labels: chore

#135 Update the requirements.txt
  requirements.txt
Labels: bug fix
