Repository fosslight/fosslight_util, pull requests merged in 2023-07, with the labels that each got.

#123 Fix the issue for correct mode
  src/fosslight_util/correct.py
  src/fosslight_util/write_excel.py
Labels: bug fix

#124 Fix the index out of range bug
  src/fosslight_util/write_excel.py
Labels: bug fix

#125 Fix the spdx to validate
  requirements.txt
  src/fosslight_util/write_spdx.py
Labels: chore

#126 Download the latest version of npm
  requirements.txt
  src/fosslight_util/_get_downloadable_url.py
Labels: enhancement
