Repository fosslight/fosslight_util, pull requests merged in 2024-09, with the labels that each got.

#175 Refactoring OssItem
  requirements-dev.txt
  src/fosslight_util/compare_yaml.py
  src/fosslight_util/constant.py
  src/fosslight_util/correct.py
  src/fosslight_util/oss_item.py
  src/fosslight_util/output_format.py
  src/fosslight_util/parsing_yaml.py
  src/fosslight_util/read_excel.py
  src/fosslight_util/write_excel.py
  src/fosslight_util/write_opossum.py
  src/fosslight_util/write_scancodejson.py
  src/fosslight_util/write_spdx.py
  src/fosslight_util/write_yaml.py
  tests/test_excel_and_csv.py
  tests/test_opossum.py
  tests/test_output_format.py
  tests/test_yaml.py
  tox.ini
Labels: chore, major

#186 Fix tox version & delete tox-wheel
  requirements-dev.txt
Labels: chore

#188 Fix the tox bug
  tox.ini
Labels: bug fix
