Repository fosslight/fosslight_util, pull requests merged in 2024-10, with the labels that each got.

#189 Refactor existing tox test to pytest
  tests/__init__.py
  tests/conftest.py
  tests/constants.py
  tests/legacy/__init__.py
  tests/legacy/_print_log.py
  tests/legacy/_print_log_with_another_logger.py
  tests/legacy/resources/FOSSLight-Report_sample.xlsx
  tests/legacy/resources/after.yaml
  tests/legacy/resources/before.yaml
  tests/legacy/test_compare_yaml.py
  tests/legacy/test_convert_to_yaml.py
  tests/legacy/test_download.py
  tests/legacy/test_excel_and_csv.py
  tests/legacy/test_help.py
  tests/legacy/test_log.py
  tests/legacy/test_opossum.py
  tests/legacy/test_output_format.py
  tests/legacy/test_spdx_licenses.py
  tests/legacy/test_text.py
  tests/legacy/test_timer.py
  tests/legacy/test_yaml.py
  tests/resources/FOSSLight-Report_sample.xlsx
  tests/resources/after.yaml
  tests/resources/before.yaml
  tests/test_download.py
  tests/test_opossum.py
  tests/test_spdx_licenses.py
  tests/test_text.py
  tests/test_write_output.py
  tests/test_write_yaml.py
  tox.ini
Labels: chore

#192 Update spdx function
  requirements-dev.txt
  requirements.txt
  src/fosslight_util/oss_item.py
  src/fosslight_util/output_format.py
  src/fosslight_util/write_spdx.py
Labels: enhancement

#190 Improving download performance when cloning based on specific branches or tags
  requirements.txt
  src/fosslight_util/download.py
  tests/test_download.py
  tox.ini
Labels: chore

#193 Fix the spdx windows issue
  requirements.txt
  src/fosslight_util/write_spdx.py
Labels: bug fix

#194 Fix the spdx bug
  src/fosslight_util/oss_item.py
  src/fosslight_util/write_spdx.py
Labels: bug fix, minor

#195 Remove unnecessary req-dev.txt
  requirements-dev.txt
Labels: chore

#196 Update compare yaml test case
  src/fosslight_util/compare_yaml.py
  src/fosslight_util/convert_excel_to_yaml.py
  tests/legacy/test_compare_yaml.py
  tests/legacy/test_convert_to_yaml.py
Labels: chore

#197 Remove spdx for macos
  requirements.txt
  src/fosslight_util/output_format.py
Labels: chore

#198 Print option name with error msg
  src/fosslight_util/output_format.py
Labels: chore
