Repository fosslight/fosslight_util, pull requests merged in 2024-11, with the labels that each got.

#200 Don't change prefix for ssh link
  src/fosslight_util/download.py
Labels: chore

#201 Add params for cloning private git
  src/fosslight_util/download.py
Labels: enhancement

#202 Support cycloneDX format
  requirements.txt
  src/fosslight_util/output_format.py
  src/fosslight_util/write_cyclonedx.py
Labels: enhancement

#203 Bug fix related to before assignment
  src/fosslight_util/download.py
Labels: bug fix
