Repository fosslight/fosslight_util, pull requests merged in 2024-07, with the labels that each got.

#166 Enable multiple input for -f and -o option
  src/fosslight_util/output_format.py
Labels: enhancement

#167 Fix to add sbom info one time
  src/fosslight_util/correct.py
Labels: chore

#168 Fix default file extension bug
  src/fosslight_util/output_format.py
Labels: bug fix

#173 Update CoverItem init for dynamic package versions
  src/fosslight_util/cover.py
Labels: chore

#171 Fix csv format column name bug
  src/fosslight_util/output_format.py
Labels: bug fix
